// JavaScript Document

// need a script to allow the input of a time value in the future and then countdown to that time...
// also allowing for multiple instances of the countdown on any given page, if needed.... 

// and perhaps a graphical representation - a 0-100% bar?  i like those :)